apiVersion: apps/v1
kind: Deployment
metadata:
  name: annual-sports-backend
  namespace: annual-sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annual-sports-backend
  template:
    metadata:
      labels:
        app: annual-sports-backend
    spec:
      containers:
        - name: backend
          image: pkprincekumar7/annual-sports-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGODB_URI
            - name: GMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GMAIL_USER
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GMAIL_APP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: annual-sports-backend
  namespace: annual-sports
spec:
  selector:
    app: annual-sports-backend
  ports:
    - port: 3001
      targetPort: 3001
